import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { ReactNode, Suspense } from "react";

export const metadata = {
  title: "SHENIANI",
  description: "Generated by create next app",
};

interface WebsiteLayoutProps {
  children: ReactNode;
}

const WebsiteLayout: React.FC<WebsiteLayoutProps> = ({ children }) => {
  return (
    <>
      <div className="flex min-h-screen flex-col">
        <div className="sticky md:py-2 lg:py-5 top-0 z-50 bg-background shadow-md w-full">
          <Navbar />
        </div>

        <div className="flex-1">
          <Suspense fallback={<>Loading</>}>
            <main className="flex-1">{children}</main>
          </Suspense>
        </div>
        <div>
          <Footer />
        </div>
      </div>
    </>
  );
};

export default WebsiteLayout;
